export const religions = [
    "Catholique",
    "Protestant",
    "Orthodoxe",
    "Autre Église Chrétienne",
    "Sunnite",
    "Chiite",
    "Ibadite",
    "Juif orthodoxe",
    "Juif conservateur",
    "Juif réformé",
    "Druze",
    "Hindou",
    "Bouddhiste",
    "Sikh",
    "Jaïn",
    "Taoïste",
    "Confucianiste",
    "Yoruba",
    "Santeria",
    "Vaudou",
    "Candomblé",
    "Religion Akan",
    "Zoroastriste",
    "Manichéiste",
    "Yazdaniste",
    "Chamaniste",
    "Shinto",
    "Athée",
    "Agnostique"
]